language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-19.0.1

script: 
    - (cd loaders && mvn clean install && cd ..)
    - (cd mvvm && mvn clean install && cd ..)
    - (cd task && mvn clean install && cd ..)


