language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-19.0.1


before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libstdc++6:i386 lib32z1
  - export COMPONENTS=build-tools-19.0.0,android-18,addon-google_apis-google-18
  - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/version-1/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
  - source ~/.android-sdk-installer/env
  - git clone https://github.com/mosabua/maven-android-sdk-deployer.git
  - ( cd maven-android-sdk-deployer ; mvn install -P 4.3 )

script: 
    - (cd loaders && mvn clean install && cd ..)
    - (cd mvvm && mvn clean install && cd ..)
    - (cd task && mvn clean install && cd ..)


